apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-core-consul-volume
  labels:
    app: edgex-core-consul-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/core-consul-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-core-consul-claim
spec:
  selector:
    matchLabels:
      app: edgex-core-consul-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-consul
spec:
  selector:
    app: edgex-core-consul
  ports:
    - port: 8400
      name: port-8400
    - port: 8500
      name: port-8500
    - port: 8600
      name: port-8600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-core-consul
  labels:
    app: edgex-core-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgex-core-consul
  template:
    metadata:
      name: edgex-core-consul
      labels:
        app: edgex-core-consul
    spec:
      volumes:
        - name: consul-volume
          persistentVolumeClaim:
            claimName: edgex-core-consul-claim
      containers:
        - name: edgex-core-consul
          image: consul:1.3.1
          ports:
            - containerPort: 8400
            - containerPort: 8500
            - containerPort: 8600
          readinessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: /consul/config
              name: consul-volume
            - mountPath: /consul/data
              name: consul-volume
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edgex-core-consul
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: consul.k8s
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: edgex-core-consul
              servicePort: 8500